export const initialData = {
    users: [
        {
            name: {
                first: "John",
                middle: "A.",
                last: "Doe",
            },
            phone: "123-456-7890",
            email: "john.doe@example.com",
            password: "Password123",
            address: {
                state: "California",
                country: "USA",
                city: "Cityville",
                street: "Main St",
                houseNumber: "123",
            },
            image: {
                url: "https://example.com/john.jpg",
                alt: "John Doe's profile picture",
            },
            isBusiness: true,
        },
        {
            name: {
                first: "Jane",
                middle: "B.",
                last: "Smith",
            },
            phone: "987-654-3210",
            email: "jane.smith@example.com",
            password: "Password456",
            address: {
                state: "Texas",
                country: "USA",
                city: "Townsville",
                street: "Elm St",
                houseNumber: "456",
            },
            image: {
                url: "https://example.com/jane.jpg",
                alt: "Jane Smith's profile picture",
            },
            isBusiness: false,
        },
        {
            name: {
                first: "Bob",
                middle: "C.",
                last: "Johnson",
            },
            phone: "555-555-5555",
            email: "bob.johnson@example.com",
            password: "Password789",
            address: {
                state: "New York",
                country: "USA",
                city: "Metropolis",
                street: "Maple Ave",
                houseNumber: "789",
            },
            image: {
                url: "https://example.com/bob.jpg",
                alt: "Bob Johnson's profile picture",
            },
            isBusiness: false,
        },
    ],
    cards: [
        {
            title: "Card Title 1",
            subtitle: "Subtitle 1",
            description: "Description for card 1",
            phone: "123-456-7890",
            email: "card1@example.com",
            web: "http://www.card1website.com",
            image: {
                url: "http://www.example.com/image1.jpg",
                alt: "Image 1",
            },
            address: {
                state: "State 1",
                country: "Country 1",
                city: "City 1",
                street: "Street 1",
                houseNumber: 123,
                zip: 45678,
            },
            bizNumber: 9999999,
            likes: [],
            user_id: "66bddd25921ec920f66f95de",
        },
        {
            title: "Card Title 2",
            subtitle: "Subtitle 2",
            description: "Description for card 2",
            phone: "987-654-3210",
            email: "card2@example.com",
            web: "http://www.card2website.com",
            image: {
                url: "http://www.example.com/image2.jpg",
                alt: "Image 2",
            },
            address: {
                state: "State 2",
                country: "Country 2",
                city: "City 2",
                street: "Street 2",
                houseNumber: 456,
                zip: 87654,
            },
            bizNumber: 9999998,
            likes: [],
            user_id: "66bddd25921ec920f66f95de",
        },
        {
            title: "Card Title 3",
            subtitle: "Subtitle 3",
            description: "Description for card 3",
            phone: "555-555-5555",
            email: "card3@example.com",
            web: "http://www.card3website.com",
            image: {
                url: "http://www.example.com/image3.jpg",
                alt: "Image 3",
            },
            address: {
                state: "State 3",
                country: "Country 3",
                city: "City 3",
                street: "Street 3",
                houseNumber: 789,
                zip: 12345,
            },
            bizNumber: 9999997,
            likes: [],
            user_id: "66bddd25921ec920f66f95de",
        },
    ],
};
